name: "Infracost Comment"
description: Posts a comment to the github pullrequest showing cloud cost estimates for Terraform.  Requires infracost/actions/setup to have been run.
inputs:
  path:
    description: The path to the infracost breakdown json that will be passed to infracost output.  For multiple paths, pass a glob pattern or a JSON array of paths.
    required: true
  behavior:
    description: The behavior to use when posting comments.  Must be one of 'update' | 'delete_and_new' | 'hide_and_new' | 'new'.
    required: false
    default: update
  target:
    description: What object should be commented on.  Must be one of '{pull|merge}_request' | 'commit'.  When 'commit', the 'behavior' option will be ignored.
    required: false
    default: pull_request
  GITHUB_TOKEN:
    description: 'The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to post the comment. This defaults to {{ github.token }}.'
    default: '${{ github.token }}'
    required: false
runs:
  using: "composite"
  steps:
    - name: Run infracost output
      shell: bash
      run: |
        infracost ${{ inputs.path }} --format github-comment --out-file comment.md
    - name: Map sticky behavior
      shell: bash
      run: |
        if [ "${{ inputs.behavior }}" = "new" ] || [ "${{ inputs.target }}" = "commit" ]; then
          echo "NEW_COMMENT=true" >> $GITHUB_ENV
        elif [ "${{ inputs.behavior }}" = "update" ]; then
          echo "STICKY_RECREATE=false" >> $GITHUB_ENV
          echo "STICKY_HIDE_AND_CREATE=false" >> $GITHUB_ENV
        elif [ "${{ inputs.behavior }}" = "delete_and_new" ]; then
          echo "STICKY_RECREATE=true" >> $GITHUB_ENV
          echo "STICKY_HIDE_AND_CREATE=false" >> $GITHUB_ENV
        elif [ "${{ inputs.behavior }}" = "hide_and_new" ]; then
          echo "STICKY_RECREATE=false" >> $GITHUB_ENV
          echo "STICKY_HIDE_AND_CREATE=true" >> $GITHUB_ENV
        else
          echo "::error::Unexpect behvaior '${{ inputs.behavior }}' must be one of: 'update' | 'delete_and_new' | 'hide_and_new' | 'new'"
          exit 1
        fi
    - name: Post sticky comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: env.USE_GH != true
      with:
        recreate: ${{ env.STICKY_RECREATE }}
        hide_and_recreate:  ${{ env.STICKY_HIDE_AND_CREATE }}
        path: comment.md
    - name: Post new to commit
      if: env.NEW_COMMENT == true
      shell: bash
      run: |
        if [ "${{ inputs.target }}" = "commit" ]; then
          if [ "${{ github.event.name }}" == "pull_request" ]; then
            gh commit comment "${{ github.event.number }}" -F comment.md
        else
          if [ "${{ github.event.name }}" == "pull_request" ]; then
            gh pr comment "${{ github.event.number }}" -F comment.md
          else
            echo "::info::Skipping  pullrequest number in github.event.number"
          fi
        fi


