name: "Infracost Comment"
description: Posts a comment to the github pullrequest showing cloud cost estimates for Terraform.  Requires infracost/actions/setup to have been run.
inputs:
  path:
    description: The path to the infracost breakdown json that will be passed to infracost output.  For multiple paths, pass a glob pattern or a JSON array of paths.
    required: true
  behavior:
    description: The behavior to use when posting comments.  Must be one of 'update' | 'delete_and_new' | 'hide_and_new' | 'new'.
    required: false
    default: update
  targetType:
    description: What object should be commented on.  Must be 'pr' or 'commit'.  When 'commit', the 'behavior' option will be ignored.
    required: false
    default: pr
  GITHUB_TOKEN:
    description: 'The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to get the list of Infracost CLI versions. This defaults to {{ github.token }}.'
    default: '${{ github.token }}'
    required: false
runs:
  using: "composite"
  steps:
    - name: Run infracost output
      shell: bash
      run: |
        infracost output --path ${{ inputs.path }} --format github-comment --out-file comment.md
    - name: Comment
      uses: infracost/compost-action@master
      with:
        bodyFile: comment.md
        behavior: ${{ inputs.behavior }}
        targetType: ${{ inputs.targetType }}
        GITHUB_TOKEN: ${{ github.token }}


