name: "Infracost Comment"
description: Posts a comment to GitHub pull request showing cloud cost estimates for Terraform. Requires infracost/actions/setup to have been run.
inputs:
  path:
    description: The path to the `infracost breakdown` JSON that will be passed to `infracost output`. For multiple paths, pass a glob pattern (e.g. "infracost_*.json", glob needs quotes) or a JSON array of paths.
    required: true
  behavior:
    description: The behavior to use when posting cost estimate comments. Must be one of 'update' | 'delete_and_new' | 'hide_and_new' | 'new'.
    required: false
    default: update
  target-type:
    description: Which objects should be commented on, either `pull_request` or `commit`.
    required: false
  github-token:
    description: 'Default to {{ github.token }}. This is the default GitHub token available to actions and is used to post comments.'
    default: '${{ github.token }}'
    required: false
outputs:
  body:
    description: 'The body of comment that was posted.'
    value: ${{ steps.compost-comment.outputs.body }}
runs:
  using: "composite"
  steps:
    - name: Run infracost output
      shell: bash

      run: |
        # validate inputs
        if [ "${{ inputs.target-type }}" = "commit" ]; then
          echo '::set-output name=target-type::commit'
        elif [ "${{ inputs.target-type }}" = "pull_request" ]; then
          echo '::set-output name=target-type::pr'
        else
          echo "::error::Invalid target-type '${{ inputs.target-type }}'.  Must be commit or pull_request."
          exit 1
        fi

        # handle multiple paths
        if jq . >/dev/null 2>&1 <<< '${{ inputs.path }}'; then
          paths=$(jq -r 'if type == "array" then map("--path " + .) | join(" ") else . end' <<< '${{ inputs.path }}')
        else
          paths="--path ${{ inputs.path }}"
        fi
        echo "::notice::Using paths: $paths"

        export INFRACOST_CI_POST_CONDITION=${{ inputs.behavior }}

        infracost output $paths --format github-comment --show-skipped --out-file comment.md

        if [ "${{ inputs.target-type }}" != "commit" ]; then
          if [ "${{ inputs.behavior }}" = "update" ]; then
            printf "\nThis comment will be updated when the cost estimate changes.\n\n" >> comment.md
          elif [ "${{ inputs.behavior }}" = "delete_and_new" ]; then
            printf "\nThis comment will be replaced when the cost estimate changes.\n\n" >> comment.md
          fi
        fi

        printf "<sub>\n" >> comment.md
        printf "  Is this comment useful? <a href=\"https://www.infracost.io/feedback/submit/?value=yes\" rel=\"noopener noreferrer\" target=\"_blank\">Yes</a>, <a href=\"https://www.infracost.io/feedback/submit/?value=no\" rel=\"noopener noreferrer\" target=\"_blank\">No</a>\n" >> comment.md
        printf "</sub>\n" >> comment.md
    - name: Comment
      id: compost-comment
      uses: infracost/compost-action@master
      with:
        bodyFile: comment.md
        behavior: ${{ inputs.behavior }}
        targetType: ${{ steps.run-infracost-output.outputs.target-type }}
        GITHUB_TOKEN: ${{ inputs.github-token }}


