name: "Infracost Comment"
description: Posts a comment to GitHub pull request showing cloud cost estimates for Terraform. Requires infracost/actions/setup to have been run.
inputs:
  path:
    description: The path to the `infracost breakdown` JSON that will be passed to `infracost output`. For multiple paths, pass a glob pattern (e.g. "infracost_*.json", glob needs quotes) or a JSON array of paths.
    required: true
  behavior:
    description: The behavior to use when posting cost estimate comments. Must be one of 'update' | 'delete-and-new' | 'hide-and-new' | 'new'.
    required: false
    default: update
  target-type:
    description: Which objects should be commented on, either `pull-request` or `commit`.
    required: false
  tag:
    description: 'Customize the comment tag. This is added to the comment as a markdown comment (hidden) to detect the previously posted comments. This is useful if you have multiple workflows that post comments to the same pull request or commit.'
    required: false
  github-token:
    description: 'Default to {{ github.token }}. This is the default GitHub token available to actions and is used to post comments. The default token permissions (https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions) work fine; `pull-requests: write` is required if you need to customize these.'
    default: '${{ github.token }}'
    required: false
runs:
  using: "composite"
  steps:
    - name: Post a Infracost comment to a GitHub pull request
      if: ${{ (inputs.target-type != 'commit') && (github.event.pull_request.number != '') }}
      shell: bash
      run: |
        infracost comment github --path ${{inputs.path}} \
                                 --repo $GITHUB_REPOSITORY \
                                 --tag "${{inputs.tag}}" \
                                 --github-token ${{inputs.github-token}} \
                                 --pull-request ${{github.event.pull_request.number}} \
                                 --behavior ${{inputs.behavior}}

    - name: Post a Infracost comment to a commit SHA
      if: ${{ (inputs.target-type == 'commit') }}
      shell: bash
      run: |
        infracost comment github --path ${{inputs.path}} \
                                 --repo $GITHUB_REPOSITORY \
                                 --tag "${{inputs.tag}}" \
                                 --github-token ${{inputs.github-token}} \
                                 --commit $GITHUB_SHA \
                                 --behavior ${{inputs.behavior}}
