name: "Infracost Comment"
description: Posts a comment to the github pullrequest showing cloud cost estimates for Terraform.  Requires infracost/actions/setup to have been run.
inputs:
  path:
    description: The path to the infracost breakdown json that will be passed to infracost output.  For multiple paths, pass a glob pattern or a JSON array of paths.
    required: true
  behavior:
    description: The behavior to use when posting comments.  Must be one of 'update' | 'delete_and_new' | 'hide_and_new' | 'new'.
    required: false
    default: update
  target:
    description: What object should be commented on.  Must be one of 'pr', 'mr', or 'commit'.  When 'commit', the 'behavior' option will be ignored.
    required: false
    default: pr
runs:
  using: "composite"
  steps:
    - name: Run infracost output
      shell: bash
      run: |
        infracost output --path ${{ inputs.path }} --format github-comment --out-file comment.md
    - name: Install compost
      shell: bash
      run: |
        npm install -g @infracost/compost
    - name: Post comment
      shell: bash
      run: |
        compost autodetect ${{ inputs.behavior }} --body-file comment.md --tag "Infracost Cost Estimates" --target-type ${{ inputs.target }}


