// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/infracost/actions/tools/scanner/internal/api/dashboard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// RunParameters provides a mock function for the type MockClient
func (_mock *MockClient) RunParameters(ctx context.Context, repoURL string, branchName string) (dashboard.RunParameters, error) {
	ret := _mock.Called(ctx, repoURL, branchName)

	if len(ret) == 0 {
		panic("no return value specified for RunParameters")
	}

	var r0 dashboard.RunParameters
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (dashboard.RunParameters, error)); ok {
		return returnFunc(ctx, repoURL, branchName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) dashboard.RunParameters); ok {
		r0 = returnFunc(ctx, repoURL, branchName)
	} else {
		r0 = ret.Get(0).(dashboard.RunParameters)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, repoURL, branchName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_RunParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunParameters'
type MockClient_RunParameters_Call struct {
	*mock.Call
}

// RunParameters is a helper method to define mock.On call
//   - ctx context.Context
//   - repoURL string
//   - branchName string
func (_e *MockClient_Expecter) RunParameters(ctx interface{}, repoURL interface{}, branchName interface{}) *MockClient_RunParameters_Call {
	return &MockClient_RunParameters_Call{Call: _e.mock.On("RunParameters", ctx, repoURL, branchName)}
}

func (_c *MockClient_RunParameters_Call) Run(run func(ctx context.Context, repoURL string, branchName string)) *MockClient_RunParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_RunParameters_Call) Return(runParameters dashboard.RunParameters, err error) *MockClient_RunParameters_Call {
	_c.Call.Return(runParameters, err)
	return _c
}

func (_c *MockClient_RunParameters_Call) RunAndReturn(run func(ctx context.Context, repoURL string, branchName string) (dashboard.RunParameters, error)) *MockClient_RunParameters_Call {
	_c.Call.Return(run)
	return _c
}
