// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/infracost/vcs/pkg/vcs"
	"github.com/infracost/vcs/pkg/vcs/comment"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVCS creates a new instance of MockVCS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVCS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVCS {
	mock := &MockVCS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVCS is an autogenerated mock type for the VCS type
type MockVCS struct {
	mock.Mock
}

type MockVCS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVCS) EXPECT() *MockVCS_Expecter {
	return &MockVCS_Expecter{mock: &_m.Mock}
}

// GenerateComment provides a mock function for the type MockVCS
func (_mock *MockVCS) GenerateComment(data comment.Data) (string, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for GenerateComment")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(comment.Data) (string, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func(comment.Data) string); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(comment.Data) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVCS_GenerateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateComment'
type MockVCS_GenerateComment_Call struct {
	*mock.Call
}

// GenerateComment is a helper method to define mock.On call
//   - data comment.Data
func (_e *MockVCS_Expecter) GenerateComment(data any) *MockVCS_GenerateComment_Call {
	return &MockVCS_GenerateComment_Call{Call: _e.mock.On("GenerateComment", data)}
}

func (_c *MockVCS_GenerateComment_Call) Run(run func(data comment.Data)) *MockVCS_GenerateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 comment.Data
		if args[0] != nil {
			arg0 = args[0].(comment.Data)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVCS_GenerateComment_Call) Return(s string, err error) *MockVCS_GenerateComment_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockVCS_GenerateComment_Call) RunAndReturn(run func(data comment.Data) (string, error)) *MockVCS_GenerateComment_Call {
	_c.Call.Return(run)
	return _c
}

// MaxCommentSize provides a mock function for the type MockVCS
func (_mock *MockVCS) MaxCommentSize() (int, comment.SizeUnit) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxCommentSize")
	}

	var r0 int
	var r1 comment.SizeUnit
	if returnFunc, ok := ret.Get(0).(func() (int, comment.SizeUnit)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() comment.SizeUnit); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(comment.SizeUnit)
	}
	return r0, r1
}

// MockVCS_MaxCommentSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxCommentSize'
type MockVCS_MaxCommentSize_Call struct {
	*mock.Call
}

// MaxCommentSize is a helper method to define mock.On call
func (_e *MockVCS_Expecter) MaxCommentSize() *MockVCS_MaxCommentSize_Call {
	return &MockVCS_MaxCommentSize_Call{Call: _e.mock.On("MaxCommentSize")}
}

func (_c *MockVCS_MaxCommentSize_Call) Run(run func()) *MockVCS_MaxCommentSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVCS_MaxCommentSize_Call) Return(n int, sizeUnit comment.SizeUnit) *MockVCS_MaxCommentSize_Call {
	_c.Call.Return(n, sizeUnit)
	return _c
}

func (_c *MockVCS_MaxCommentSize_Call) RunAndReturn(run func() (int, comment.SizeUnit)) *MockVCS_MaxCommentSize_Call {
	_c.Call.Return(run)
	return _c
}

// PostComment provides a mock function for the type MockVCS
func (_mock *MockVCS) PostComment(ctx context.Context, body string, behavior vcs.Behavior) (vcs.PostResult, error) {
	ret := _mock.Called(ctx, body, behavior)

	if len(ret) == 0 {
		panic("no return value specified for PostComment")
	}

	var r0 vcs.PostResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, vcs.Behavior) (vcs.PostResult, error)); ok {
		return returnFunc(ctx, body, behavior)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, vcs.Behavior) vcs.PostResult); ok {
		r0 = returnFunc(ctx, body, behavior)
	} else {
		r0 = ret.Get(0).(vcs.PostResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, vcs.Behavior) error); ok {
		r1 = returnFunc(ctx, body, behavior)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVCS_PostComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostComment'
type MockVCS_PostComment_Call struct {
	*mock.Call
}

// PostComment is a helper method to define mock.On call
//   - ctx context.Context
//   - body string
//   - behavior vcs.Behavior
func (_e *MockVCS_Expecter) PostComment(ctx any, body any, behavior any) *MockVCS_PostComment_Call {
	return &MockVCS_PostComment_Call{Call: _e.mock.On("PostComment", ctx, body, behavior)}
}

func (_c *MockVCS_PostComment_Call) Run(run func(ctx context.Context, body string, behavior vcs.Behavior)) *MockVCS_PostComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 vcs.Behavior
		if args[2] != nil {
			arg2 = args[2].(vcs.Behavior)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVCS_PostComment_Call) Return(postResult vcs.PostResult, err error) *MockVCS_PostComment_Call {
	_c.Call.Return(postResult, err)
	return _c
}

func (_c *MockVCS_PostComment_Call) RunAndReturn(run func(ctx context.Context, body string, behavior vcs.Behavior) (vcs.PostResult, error)) *MockVCS_PostComment_Call {
	_c.Call.Return(run)
	return _c
}

// SourceLink provides a mock function for the type MockVCS
func (_mock *MockVCS) SourceLink(repoURL string, commitSHA string, path string, startLine int) string {
	ret := _mock.Called(repoURL, commitSHA, path, startLine)

	if len(ret) == 0 {
		panic("no return value specified for SourceLink")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string, string, int) string); ok {
		r0 = returnFunc(repoURL, commitSHA, path, startLine)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockVCS_SourceLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceLink'
type MockVCS_SourceLink_Call struct {
	*mock.Call
}

// SourceLink is a helper method to define mock.On call
//   - repoURL string
//   - commitSHA string
//   - path string
//   - startLine int
func (_e *MockVCS_Expecter) SourceLink(repoURL any, commitSHA any, path any, startLine any) *MockVCS_SourceLink_Call {
	return &MockVCS_SourceLink_Call{Call: _e.mock.On("SourceLink", repoURL, commitSHA, path, startLine)}
}

func (_c *MockVCS_SourceLink_Call) Run(run func(repoURL string, commitSHA string, path string, startLine int)) *MockVCS_SourceLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVCS_SourceLink_Call) Return(s string) *MockVCS_SourceLink_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockVCS_SourceLink_Call) RunAndReturn(run func(repoURL string, commitSHA string, path string, startLine int) string) *MockVCS_SourceLink_Call {
	_c.Call.Return(run)
	return _c
}
