// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Push provides a mock function for the type MockClient
func (_mock *MockClient) Push(ctx context.Context, event string, extra ...interface{}) {
	if len(extra) > 0 {
		_mock.Called(ctx, event, extra)
	} else {
		_mock.Called(ctx, event)
	}

	return
}

// MockClient_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockClient_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - event string
//   - extra ...interface{}
func (_e *MockClient_Expecter) Push(ctx interface{}, event interface{}, extra ...interface{}) *MockClient_Push_Call {
	return &MockClient_Push_Call{Call: _e.mock.On("Push",
		append([]interface{}{ctx, event}, extra...)...)}
}

func (_c *MockClient_Push_Call) Run(run func(ctx context.Context, event string, extra ...interface{})) *MockClient_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_Push_Call) Return() *MockClient_Push_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Push_Call) RunAndReturn(run func(ctx context.Context, event string, extra ...interface{})) *MockClient_Push_Call {
	_c.Run(run)
	return _c
}
