name: Run examples
'on':
  push:
    branches:
      - master
  pull_request: {}
defaults:
  run:
    shell: bash
jobs:
  multi-project-config-file:
    name: Multi-project config file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Run Infracost
        run: >-
          infracost breakdown
          --config-file=examples/multi-project/code/infracost.yml --format=json
          --out-file=/tmp/infracost.json
        env:
          DEV_AWS_ACCESS_KEY_ID: ${{ secrets.EXAMPLE_DEV_AWS_ACCESS_KEY_ID }}
          DEV_AWS_SECRET_ACCESS_KEY: ${{ secrets.EXAMPLE_DEV_AWS_SECRET_ACCESS_KEY }}
          PROD_AWS_ACCESS_KEY_ID: ${{ secrets.EXAMPLE_PROD_AWS_ACCESS_KEY_ID }}
          PROD_AWS_SECRET_ACCESS_KEY: ${{ secrets.EXAMPLE_PROD_AWS_SECRET_ACCESS_KEY }}
      - name: Post Infracost comment
        run: |-
          infracost comment github --path /tmp/infracost.json \
          --repo $GITHUB_REPOSITORY \
          --github-token ${{github.token}} \
          --pull-request ${{github.event.pull_request.number}} \
          --behavior update \
          --dry-run true \
          > infracost-comment.md
      - run: >-
          diff -y ./testdata/multi-project-config-file_comment_golden.md
          infracost-comment.md
        name: Check the comment
      - name: Update the golden comment file
        run: >-
          cp /tmp/infracost_comment.md
          ./testdata/multi-project-config-file_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES == 'true'
  multi-project-matrix:
    name: Multi-project matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: dev
            aws_access_key_id_secret: EXAMPLE_DEV_AWS_ACCESS_KEY_ID
            aws_secret_access_key_secret: EXAMPLE_DEV_AWS_SECRET_ACCESS_KEY
          - dir: prod
            aws_access_key_id_secret: EXAMPLE_PROD_AWS_ACCESS_KEY_ID
            aws_secret_access_key_secret: EXAMPLE_PROD_AWS_SECRET_ACCESS_KEY
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Run Infracost
        run: >-
          infracost breakdown --path=examples/multi-project/code/${{ matrix.dir
          }} --format=json --out-file=/tmp/infracost_${{ matrix.dir }}.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets[matrix.aws_access_key_id_secret] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[matrix.aws_secret_access_key_secret] }}
      - name: Upload Infracost breakdown
        uses: actions/upload-artifact@v2
        with:
          name: infracost_jsons
          path: /tmp/infracost_${{ matrix.dir }}.json
    if: github.actor != 'nektos/act'
  multi-project-matrix-merge:
    name: Multi-project matrix merge
    runs-on: ubuntu-latest
    needs:
      - multi-project-matrix
    steps:
      - uses: actions/checkout@v2
      - name: Download all Infracost breakdown files
        uses: actions/download-artifact@v2
        with:
          path: /tmp
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Post Infracost comment
        run: |-
          infracost comment github --path "/tmp/infracost_jsons/*.json" \
          --repo $GITHUB_REPOSITORY \
          --github-token ${{github.token}} \
          --pull-request ${{github.event.pull_request.number}} \
          --behavior update \
          --dry-run true \
          > infracost-comment.md
      - run: >-
          diff -y ./testdata/multi-project-matrix-merge_comment_golden.md
          infracost-comment.md
        name: Check the comment
      - name: Update the golden comment file
        run: >-
          cp /tmp/infracost_comment.md
          ./testdata/multi-project-matrix-merge_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES == 'true'
    if: github.actor != 'nektos/act'
  multi-terraform-workspace-config-file:
    name: Multi-Terraform workspace config file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Run Infracost
        run: >-
          infracost breakdown
          --config-file=examples/multi-terraform-workspace/code/infracost.yml
          --format=json --out-file=/tmp/infracost.json
        env:
          DEV_AWS_ACCESS_KEY_ID: ${{ secrets.EXAMPLE_DEV_AWS_ACCESS_KEY_ID }}
          DEV_AWS_SECRET_ACCESS_KEY: ${{ secrets.EXAMPLE_DEV_AWS_SECRET_ACCESS_KEY }}
          PROD_AWS_ACCESS_KEY_ID: ${{ secrets.EXAMPLE_PROD_AWS_ACCESS_KEY_ID }}
          PROD_AWS_SECRET_ACCESS_KEY: ${{ secrets.EXAMPLE_PROD_AWS_SECRET_ACCESS_KEY }}
      - name: Post Infracost comment
        run: |-
          infracost comment github --path /tmp/infracost.json \
          --repo $GITHUB_REPOSITORY \
          --github-token ${{github.token}} \
          --pull-request ${{github.event.pull_request.number}} \
          --behavior update \
          --dry-run true \
          > infracost-comment.md
      - run: >-
          diff -y
          ./testdata/multi-terraform-workspace-config-file_comment_golden.md
          infracost-comment.md
        name: Check the comment
      - name: Update the golden comment file
        run: >-
          cp /tmp/infracost_comment.md
          ./testdata/multi-terraform-workspace-config-file_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES == 'true'
  private-terraform-module:
    name: Private Terraform module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: add GIT_SSH_KEY
        run: >
          mkdir -p .ssh

          echo "${{ secrets.GIT_SSH_KEY }}" > .ssh/git_ssh_key

          chmod 400 .ssh/git_ssh_key

          echo "GIT_SSH_COMMAND=ssh -i $(pwd)/.ssh/git_ssh_key -o
          'StrictHostKeyChecking=no'" >> $GITHUB_ENV
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Run Infracost
        run: >-
          infracost breakdown --path=examples/private-terraform-module/code
          --format=json --out-file=/tmp/infracost.json
      - name: Post Infracost comment
        run: |-
          infracost comment github --path /tmp/infracost.json \
          --repo $GITHUB_REPOSITORY \
          --github-token ${{github.token}} \
          --pull-request ${{github.event.pull_request.number}} \
          --behavior update \
          --dry-run true \
          > infracost-comment.md
      - run: >-
          diff -y ./testdata/private-terraform-module_comment_golden.md
          infracost-comment.md
        name: Check the comment
      - name: Update the golden comment file
        run: >-
          cp /tmp/infracost_comment.md
          ./testdata/private-terraform-module_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES == 'true'
  sentinel:
    name: Sentinel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Setup Sentinel
        run: >
          mkdir /tmp/sentinel

          curl -o /tmp/sentinel/sentinel.zip
          https://releases.hashicorp.com/sentinel/0.18.4/sentinel_0.18.4_linux_amd64.zip

          unzip -d /tmp/sentinel /tmp/sentinel/sentinel.zip

          echo "/tmp/sentinel" >> $GITHUB_PATH
      - name: Run Infracost
        run: >-
          infracost breakdown --path=examples/sentinel/code/plan.json
          --format=json --out-file=/tmp/infracost.json
      - name: Run Sentinel
        run: >-
          sentinel apply -global breakdown="$(cat /tmp/infracost.json)"
          examples/sentinel/policy/policy.policy | tee /tmp/sentinel.out
      - name: Check Policies
        run: |
          result=$(</tmp/sentinel.out)
          if [ "$result" != "Pass - policy.policy" ]; then
            echo -e "::error::Policy check failed:\n$result"
            exit 1
          else
            echo "::info::Policy check passed."
          fi
  slack:
    name: Slack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Generate Infracost JSON
        run: >-
          infracost breakdown --path=examples/slack/code/plan.json --format json
          --out-file /tmp/infracost.json
      - name: Post Infracost comment
        run: |-
          infracost comment github --path /tmp/infracost.json \
          --repo $GITHUB_REPOSITORY \
          --github-token ${{github.token}} \
          --pull-request ${{github.event.pull_request.number}} \
          --behavior update \
          --dry-run true \
          > infracost-comment.md
      - run: diff -y ./testdata/slack_comment_golden.md infracost-comment.md
        name: Check the comment
      - name: Update the golden comment file
        run: cp /tmp/infracost_comment.md ./testdata/slack_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES == 'true'
      - name: Generate Slack message
        id: infracost-slack
        run: >
          echo "::set-output name=slack-message::$(infracost output --path
          /tmp/infracost.json --format slack-message --show-skipped)"

          echo "::set-output name=diffTotalMonthlyCost::$(jq
          '(.diffTotalMonthlyCost // 0) | tonumber' /tmp/infracost.json)"
      - name: Generate Slack message
        run: >-
          infracost output --path=/tmp/infracost.json --format=slack-message
          --show-skipped --out-file=/tmp/infracost_slack_message.json
      - name: Check the Slack message
        run: >-
          diff -y <(jq --sort-keys . ./testdata/slack_slack_message_golden.json)
          <(jq --sort-keys . /tmp/infracost_slack_message.json)
        if: env.UPDATE_GOLDEN_FILES != 'true'
      - name: Update the golden Slack message file
        run: >-
          jq --sort-keys . /tmp/infracost_slack_message.json >
          ./testdata/slack_slack_message_golden.json
        if: env.UPDATE_GOLDEN_FILES == 'true'
  terraform-cloud-enterprise:
    name: Terraform Cloud/Enterprise
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Run Infracost
        run: >-
          infracost breakdown --path=examples/terraform-cloud-enterprise/code
          --format=json --out-file=/tmp/infracost.json
        env:
          INFRACOST_TERRAFORM_CLOUD_TOKEN: ${{ secrets.TFC_TOKEN }}
      - name: Post Infracost comment
        run: |-
          infracost comment github --path /tmp/infracost.json \
          --repo $GITHUB_REPOSITORY \
          --github-token ${{github.token}} \
          --pull-request ${{github.event.pull_request.number}} \
          --behavior update \
          --dry-run true \
          > infracost-comment.md
      - run: >-
          diff -y ./testdata/terraform-cloud-enterprise_comment_golden.md
          infracost-comment.md
        name: Check the comment
      - name: Update the golden comment file
        run: >-
          cp /tmp/infracost_comment.md
          ./testdata/terraform-cloud-enterprise_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES == 'true'
  terraform-directory:
    name: Terraform directory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Run Infracost
        run: >-
          infracost breakdown --path=examples/terraform-directory/code
          --format=json --out-file=/tmp/infracost.json
      - name: Post Infracost comment
        run: |-
          infracost comment github --path /tmp/infracost.json \
          --repo $GITHUB_REPOSITORY \
          --github-token ${{github.token}} \
          --pull-request ${{github.event.pull_request.number}} \
          --behavior update \
          --dry-run true \
          > infracost-comment.md
      - run: >-
          diff -y ./testdata/terraform-directory_comment_golden.md
          infracost-comment.md
        name: Check the comment
      - name: Update the golden comment file
        run: >-
          cp /tmp/infracost_comment.md
          ./testdata/terraform-directory_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES == 'true'
  terraform-plan-json:
    name: Terraform plan JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Run Infracost
        run: >-
          infracost breakdown --path=examples/terraform-plan-json/code/plan.json
          --format=json --out-file=/tmp/infracost.json
      - name: Post Infracost comment
        run: |-
          infracost comment github --path /tmp/infracost.json \
          --repo $GITHUB_REPOSITORY \
          --github-token ${{github.token}} \
          --pull-request ${{github.event.pull_request.number}} \
          --behavior update \
          --dry-run true \
          > infracost-comment.md
      - run: >-
          diff -y ./testdata/terraform-plan-json_comment_golden.md
          infracost-comment.md
        name: Check the comment
      - name: Update the golden comment file
        run: >-
          cp /tmp/infracost_comment.md
          ./testdata/terraform-plan-json_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES == 'true'
  terragrunt:
    name: Terragrunt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.35.9
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Run Infracost
        run: >-
          infracost breakdown --path=examples/terragrunt/code --format=json
          --out-file=/tmp/infracost.json
      - name: Post Infracost comment
        run: |-
          infracost comment github --path /tmp/infracost.json \
          --repo $GITHUB_REPOSITORY \
          --github-token ${{github.token}} \
          --pull-request ${{github.event.pull_request.number}} \
          --behavior update \
          --dry-run true \
          > infracost-comment.md
      - run: diff -y ./testdata/terragrunt_comment_golden.md infracost-comment.md
        name: Check the comment
      - name: Update the golden comment file
        run: cp /tmp/infracost_comment.md ./testdata/terragrunt_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES == 'true'
