name: Run examples
'on':
  push:
    branches:
      - master
  pull_request: {}
defaults:
  run:
    shell: bash
jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - dev
          - prod
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.35.9
      - name: Setup Infracost
        uses: ./setup
        with:
          api_key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Run Infracost
        run: >-
          infracost breakdown --path=examples/matrix/code/${{ matrix.dir }}
          --format=json --out-file=/tmp/infracost_breakdown_${{ matrix.dir
          }}.json
      - name: Upload Infracost breakdown
        uses: actions/upload-artifact@v2
        with:
          name: infracost_breakdown_${{ matrix.dir }}.json
          path: infracost_breakdown_${{ matrix.dir }}.json
  matrix_merge:
    name: Matrix merge
    runs-on: ubuntu-latest
    needs:
      - matrix
    steps:
      - name: Download all Infracost breakdown files
        id: download
        uses: actions/download-artifact@v2
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      - name: ls
        run: ls
      - name: ls
        run: ls ${{steps.download.outputs.download-path}}
  terragrunt:
    name: Terragrunt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.35.9
      - name: Setup Infracost
        uses: ./setup
        with:
          api_key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Run Infracost
        run: >-
          infracost breakdown --path=examples/terragrunt/code --format=json
          --out-file=/tmp/infracost_breakdown.json
      - name: Generate Infracost comment
        run: >-
          infracost output --path=/tmp/infracost_breakdown.json
          --format=github-comment --out-file=/tmp/infracost_comment.md
      - name: Check the comment
        run: diff /tmp/infracost_comment.md ./testdata/terragrunt_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES != 'true'
      - name: Update the golden comment file
        run: cp /tmp/infracost_comment.md ./testdata/terragrunt_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES == 'true'
