name: Test Comment

on:
  push:
    branches:
      - master
    paths:
      - "get-comment/**"
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test_get_comment:
    name: Test Get Comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup infracost
        uses: ./setup
        with:
          api-key: abcdefg123456

      - name: Save comment output
        run: |
          infracost comment github --path ./testdata/comment/simple_breakdown.json \
                                   --repo $GITHUB_REPOSITORY \
                                   --github-token ${{github.token}} \
                                   --pull-request ${{github.event.pull_request.number}} \
                                   --behavior new \
                                   --dry-run true \
                                   > expected.md

          head -n -2 expected.md > tmp.txt && mv tmp.txt expected.md

      - name: Infracost comment
        id: post-comment
        uses: ./comment
        with:
          path: ./testdata/comment/simple_breakdown.json
          tag: "custom-tag"
          behavior: new

      - name: Infracost get comment
        id: get-comment
        uses: ./get-comment
        with:
          tag: "custom-tag"

      - run: |
          actual=$(cat <<\EOF
          ${{ steps.get-comment.outputs.body }}
          EOF
          )
          diff -y <(echo "$actual") expected.md
        name: Check the comment