name: Scanner
on:
  push:
    branches:
      - master
    paths:
      - tools/scanner/**
  pull_request:
    paths:
      - tools/scanner/**

defaults:
  run:
    shell: bash
    working-directory: tools/scanner

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          go-version-file: tools/scanner/go.mod
          cache-dependency-path: tools/scanner/go.sum

      - run: make test-unit

  integration:
    name: Integration Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          go-version-file: tools/scanner/go.mod
          cache-dependency-path: tools/scanner/go.sum

      - uses: actions/cache@v4
        with:
          path: ~/.cache/infracost/plugins
          key: ${{ runner.os }}-scanner-plugins

      - run: make test-integration
        env:
          INFRACOST_CLI_AUTHENTICATION_TOKEN: ${{ secrets.INFRACOST_CLI_AUTHENTICATION_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          go-version-file: tools/scanner/go.mod
          cache-dependency-path: tools/scanner/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10
          working-directory: tools/scanner

  mocks:
    name: Mocks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          go-version-file: tools/scanner/go.mod
          cache-dependency-path: tools/scanner/go.sum

      - run: make mocks

      - name: Check for changes
        run: |
          if [ -n "$(git diff --name-only)" ]; then
            echo "Mock files are out of date. Please run 'make mocks' and commit the changes."
            git diff --name-only
            exit 1
          fi