name: Verify dist is up to date (npm run prepare)

on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  verify-dist:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: npm install

      - name: Rebuild dist (npm run prepare)
        run: npm run prepare

      - name: Verify no dist changes
        run: |
          if [ -n "$(git status dist --porcelain)" ]; then
            # Uncommitted changes
            git status dist --porcelain
            echo "::error::Uncommitted changes after npm run prepare.  Run 'npm run prepare' and commit any changes to ./dist."
            exit 1
          fi

